server:
  port: 9093

spring:
  jackson:
    visibility:
      field: any
    serialization:
      indent_output: true
credentials:
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}